server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    resolver 127.0.0.11 valid=30s;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Access-Control-Allow-Origin "*";
    }

    # All API and WebSocket traffic goes to the backend
    location /api/ {
        set $backend http://music-backend:3000;
        proxy_pass         $backend;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host       $host;
    }

    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options        SAMEORIGIN;
}
